### ISSUE TITLE
If this was copied from pymedphys, it should reference it, and presumably honour it's license...

### ISSUE THREAD

**Issue by SimonBiggs** [RadiotherapyAI/RadiotherapyAI#75]
If this was copied from pymedphys, it should reference it, and presumably honour it's license...

_Originally posted by @sjswerdloff in https://github.com/RadiotherapyAI/RadiotherapyAI/pull/71#discussion_r974997985_

**Comment by SimonBiggs** [comment]
If we go back in time to when the PyMedPhys version was originally written, it was actually under the AGPLv3.0 with the same additional terms as being used within this repo :)

https://github.com/pymedphys/pymedphys/blame/e0253ff0f7940f23ef6b039acc7bd1d1ba6cf8cf/src/pymedphys/dcm/_level1/dcmcreate.py

... and it was entirely written by myself. And for the purpose of this repo, I am handing all of my copyright over to `Radiotherapy AI Holdings Pty Ltd`.

Let me know if that alleviates your concerns.

**Comment by sjswerdloff** [comment]
Totally, especially now that this is documented here!

**Comment by SimonBiggs** [comment]
Awesome :slightly_smiling_face:, thanks @sjswerdloff :slightly_smiling_face:
